version: "3"

services:

   app:

    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: apivendas-app
    ports:
      - "3333:3333"
    volumes:
      - .:/home/node/app
    depends_on:
      - db
      - redis

   db:

    build: .docker/postgres
    container_name: apivendas-db
    restart: always
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
     - POSTGRES_PASSWORD=docker
     - POSTGRES_DB=apivendas

   redis:

    image: 'redis:latest'
    container_name: apivendas-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
   pgadmin:

     image: dpage/pgadmin4
     container_name: apivendas-pgadmin
     tty: true
     environment:
       - PGADMIN_DEFAULT_EMAIL=andreraizdetudo@gmail.com
       - PGADMIN_DEFAULT_PASSWORD=docker
     ports:
       - "5050:80"
     depends_on:
       - db





